[package]
name = "dvs-cli"
description = """
Command-line interface for DVS (Data Version System).
"""
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "dvs"
path = "src/main.rs"

[dependencies]
dvs-core.workspace = true
clap = { version = "4.5", features = ["derive"] }
thiserror.workspace = true
fs-err.workspace = true
